### ISSUE TITLE
Dealing with categorical logs in welly

### ISSUE THREAD

**Issue by justyna-przybysz** [agilescientific/welly#163]
Currently, to my knowledge, welly uses interpolation when equalizing basis, or resampling to new basis. This does not take into account that some curves represented in .las maybe of categorical nature and coded with integers. Any plans to take that into account?

**Comment by kwinkunks** [comment]
Good point. Thank you for thinking about this.

It wouldn't be too hard to implement, because `scipy` has various interpolation methods, including nearest, previous, etc. 

In the meantime, it's not all that convenient but you could use `striplog` for this too — `striplog.from_log()` then `striplog.to_log()` would do it I think.

**Comment by justyna-przybysz** [comment]
Thanks.

**Comment by frank1010111** [comment]
Interpolation on categorical data should be fixed in #241.
